//! MySQL driver with rustls support and prepared positional parameters.
use mysql::{Conn,Opts,Params,Row,Value as MyValue,prelude::Queryable};
use std::collections::BTreeMap;
use std::sync::{Arc,Condvar,Mutex};
use std::time::{Duration,Instant};
use thiserror::Error;
#[derive(Debug,Clone,PartialEq)]pub enum DbValue{Null,Integer(i64),Unsigned(u64),Real(f64),Text(String),Bytes(Vec<u8>),Date(String),Time(String)}
#[derive(Error,Debug)]pub enum MyError{#[error("MySQL error: {0}")]Mysql(#[from]mysql::Error),#[error("invalid MySQL URL: {0}")]Url(#[from]mysql::UrlError),#[error("transaction already active")]TransactionActive,#[error("no active transaction")]NoTransaction,#[error("MySQL pool size must be positive")]PoolSize,#[error("MySQL pool acquisition timed out")]PoolTimeout,#[error("MySQL pool is closed")]PoolClosed,#[error("MySQL pool lock poisoned")]PoolPoisoned,#[error("migration versions must be positive, unique, and increasing")]MigrationOrder,#[error("previously applied migration {version} has changed")]MigrationChanged{version:i64},#[error("could not acquire MySQL migration lock")]MigrationLock}
#[derive(Debug,Clone)]pub struct Migration{pub version:i64,pub name:String,pub sql:String}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct AppliedMigration{pub version:i64,pub name:String,pub checksum:String}
pub struct Database{connection:Conn,in_transaction:bool}
impl Database{pub fn connect(url:&str)->Result<Self,MyError>{let options=Opts::from_url(url)?;Ok(Self{connection:Conn::new(options)?,in_transaction:false})}
pub fn execute(&mut self,sql:&str,params:&[DbValue])->Result<u64,MyError>{self.connection.exec_drop(sql,Params::Positional(params.iter().map(to_mysql).collect()))?;Ok(self.connection.affected_rows())}
pub fn query(&mut self,sql:&str,params:&[DbValue])->Result<Vec<BTreeMap<String,DbValue>>,MyError>{let rows:Vec<Row>=self.connection.exec(sql,Params::Positional(params.iter().map(to_mysql).collect()))?;Ok(rows.into_iter().map(row).collect())}
pub fn begin(&mut self)->Result<(),MyError>{if self.in_transaction{return Err(MyError::TransactionActive)}self.connection.query_drop("START TRANSACTION")?;self.in_transaction=true;Ok(())}
pub fn commit(&mut self)->Result<(),MyError>{if !self.in_transaction{return Err(MyError::NoTransaction)}self.connection.query_drop("COMMIT")?;self.in_transaction=false;Ok(())}
pub fn rollback(&mut self)->Result<(),MyError>{if !self.in_transaction{return Err(MyError::NoTransaction)}self.connection.query_drop("ROLLBACK")?;self.in_transaction=false;Ok(())}
pub fn migrate(&mut self,migrations:&[Migration])->Result<usize,MyError>{validate_migrations(migrations)?;let locked:Option<u8>=self.connection.query_first("SELECT GET_LOCK('titan_migrations',30)")?;if locked!=Some(1){return Err(MyError::MigrationLock)}let result=self.migrate_locked(migrations);let unlock=self.connection.query_drop("SELECT RELEASE_LOCK('titan_migrations')");match(result,unlock){(Ok(count),Ok(()))=>Ok(count),(Err(error),_)=>Err(error),(_,Err(error))=>Err(error.into())}}
fn migrate_locked(&mut self,migrations:&[Migration])->Result<usize,MyError>{self.connection.query_drop("CREATE TABLE IF NOT EXISTS _titan_migrations(version BIGINT PRIMARY KEY,name VARCHAR(255) NOT NULL,checksum VARCHAR(64) NOT NULL,applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)")?;let applied=self.applied_migrations()?.into_iter().map(|migration|(migration.version,migration)).collect::<BTreeMap<_,_>>();for migration in migrations{if let Some(existing)=applied.get(&migration.version){if existing.name!=migration.name||existing.checksum!=checksum(&migration.sql){return Err(MyError::MigrationChanged{version:migration.version})}}}let mut count=0;for migration in migrations{if applied.contains_key(&migration.version){continue}self.connection.query_drop(&migration.sql)?;self.connection.exec_drop("INSERT INTO _titan_migrations(version,name,checksum) VALUES (?,?,?)",(migration.version,&migration.name,checksum(&migration.sql)))?;count+=1;}Ok(count)}
pub fn applied_migrations(&mut self)->Result<Vec<AppliedMigration>,MyError>{Ok(self.connection.query_map("SELECT version,name,checksum FROM _titan_migrations ORDER BY version",|(version,name,checksum)|AppliedMigration{version,name,checksum})?)}
pub fn last_insert_id(&self)->u64{self.connection.last_insert_id()}}
impl Drop for Database{fn drop(&mut self){if self.in_transaction{let _=self.connection.query_drop("ROLLBACK");}}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub struct PoolStats{pub maximum:usize,pub total:usize,pub idle:usize,pub checked_out:usize,pub closed:bool}
struct PoolState{idle:Vec<Database>,total:usize,closed:bool}struct PoolInner{url:String,maximum:usize,state:Mutex<PoolState>,available:Condvar}
#[derive(Clone)]pub struct Pool(Arc<PoolInner>);pub struct PooledConnection{database:Option<Database>,pool:Arc<PoolInner>}
impl Pool{pub fn new(url:impl Into<String>,maximum:usize)->Result<Self,MyError>{if maximum==0{return Err(MyError::PoolSize)}Ok(Self(Arc::new(PoolInner{url:url.into(),maximum,state:Mutex::new(PoolState{idle:Vec::new(),total:0,closed:false}),available:Condvar::new()})))}
pub fn acquire(&self,timeout:Duration)->Result<PooledConnection,MyError>{let deadline=Instant::now()+timeout;loop{let mut state=self.0.state.lock().map_err(|_|MyError::PoolPoisoned)?;if state.closed{return Err(MyError::PoolClosed);}
if let Some(database)=state.idle.pop(){return Ok(PooledConnection{database:Some(database),pool:Arc::clone(&self.0)});}
if state.total<self.0.maximum{state.total+=1;drop(state);match Database::connect(&self.0.url){Ok(database)=>return Ok(PooledConnection{database:Some(database),pool:Arc::clone(&self.0)}),Err(error)=>{let mut state=self.0.state.lock().map_err(|_|MyError::PoolPoisoned)?;state.total-=1;self.0.available.notify_one();return Err(error)}}}let remaining=deadline.saturating_duration_since(Instant::now());if remaining.is_zero(){return Err(MyError::PoolTimeout);}let(_guard,wait)=self.0.available.wait_timeout(state,remaining).map_err(|_|MyError::PoolPoisoned)?;if wait.timed_out(){return Err(MyError::PoolTimeout);}}}
pub fn stats(&self)->Result<PoolStats,MyError>{let state=self.0.state.lock().map_err(|_|MyError::PoolPoisoned)?;Ok(PoolStats{maximum:self.0.maximum,total:state.total,idle:state.idle.len(),checked_out:state.total-state.idle.len(),closed:state.closed})}pub fn close(&self)->Result<(),MyError>{let mut state=self.0.state.lock().map_err(|_|MyError::PoolPoisoned)?;state.closed=true;let idle=state.idle.len();state.idle.clear();state.total-=idle;self.0.available.notify_all();Ok(())}}
impl std::ops::Deref for PooledConnection{type Target=Database;fn deref(&self)->&Self::Target{self.database.as_ref().expect("pool invariant")}}impl std::ops::DerefMut for PooledConnection{fn deref_mut(&mut self)->&mut Self::Target{self.database.as_mut().expect("pool invariant")}}impl Drop for PooledConnection{fn drop(&mut self){let Some(database)=self.database.take()else{return};if let Ok(mut state)=self.pool.state.lock(){if state.closed{state.total=state.total.saturating_sub(1)}else{state.idle.push(database)}self.pool.available.notify_one();}}}
fn validate_migrations(migrations:&[Migration])->Result<(),MyError>{let mut previous=0;for migration in migrations{if migration.version<=previous{return Err(MyError::MigrationOrder)}previous=migration.version;}Ok(())}
fn checksum(sql:&str)->String{let mut hash=0xcbf29ce484222325u64;for byte in sql.as_bytes(){hash^=u64::from(*byte);hash=hash.wrapping_mul(0x100000001b3);}format!("fnv1a64:{hash:016x}")}
fn to_mysql(value:&DbValue)->MyValue{match value{DbValue::Null=>MyValue::NULL,DbValue::Integer(value)=>MyValue::Int(*value),DbValue::Unsigned(value)=>MyValue::UInt(*value),DbValue::Real(value)=>MyValue::Double(*value),DbValue::Text(value)=>MyValue::Bytes(value.as_bytes().to_vec()),DbValue::Bytes(value)=>MyValue::Bytes(value.clone()),DbValue::Date(value)|DbValue::Time(value)=>MyValue::Bytes(value.as_bytes().to_vec())}}
fn row(row:Row)->BTreeMap<String,DbValue>{let names:Vec<String>=row.columns_ref().iter().map(|column|column.name_str().into_owned()).collect();row.unwrap().into_iter().enumerate().map(|(index,value)|(names[index].clone(),from_mysql(value))).collect()}
fn from_mysql(value:MyValue)->DbValue{match value{MyValue::NULL=>DbValue::Null,MyValue::Int(value)=>DbValue::Integer(value),MyValue::UInt(value)=>DbValue::Unsigned(value),MyValue::Float(value)=>DbValue::Real(value.into()),MyValue::Double(value)=>DbValue::Real(value),MyValue::Bytes(value)=>String::from_utf8(value).map(DbValue::Text).unwrap_or_else(|error|DbValue::Bytes(error.into_bytes())),MyValue::Date(year,month,day,hour,minute,second,micros)=>DbValue::Date(format!("{year:04}-{month:02}-{day:02} {hour:02}:{minute:02}:{second:02}.{micros:06}")),MyValue::Time(negative,days,hours,minutes,seconds,micros)=>DbValue::Time(format!("{}{days} {hours:02}:{minutes:02}:{seconds:02}.{micros:06}",if negative{"-"}else{""}))}}
#[cfg(test)]mod tests{use super::*;#[test]fn validates_migration_order_and_checksums_without_server(){let valid=vec![Migration{version:1,name:"one".into(),sql:"SELECT 1".into()},Migration{version:2,name:"two".into(),sql:"SELECT 2".into()}];assert!(validate_migrations(&valid).is_ok());assert!(validate_migrations(&[Migration{version:2,name:"two".into(),sql:"".into()},Migration{version:1,name:"one".into(),sql:"".into()}]).is_err());assert_ne!(checksum("SELECT 1"),checksum("SELECT 2"));}#[test]fn validates_pool_lifecycle_without_server(){assert!(matches!(Pool::new("mysql://localhost/test",0),Err(MyError::PoolSize)));let pool=Pool::new("mysql://localhost/test",1).unwrap();pool.close().unwrap();assert!(matches!(pool.acquire(Duration::ZERO),Err(MyError::PoolClosed)));}#[test]fn converts_all_mysql_value_variants(){let values=vec![MyValue::NULL,MyValue::Int(-1),MyValue::UInt(1),MyValue::Float(1.5),MyValue::Double(2.5),MyValue::Bytes(b"text".to_vec()),MyValue::Date(2026,7,15,1,2,3,4),MyValue::Time(false,1,2,3,4,5)];assert_eq!(values.into_iter().map(from_mysql).count(),8);}#[test]fn live_mysql_round_trip_when_configured(){let Ok(url)=std::env::var("TITAN_MYSQL_TEST_URL")else{return};let mut db=Database::connect(&url).unwrap();let rows=db.query("SELECT ? AS value",&[DbValue::Integer(42)]).unwrap();assert!(matches!(rows[0]["value"],DbValue::Integer(42)|DbValue::Unsigned(42)));}}
