//! MySQL driver with rustls support and prepared positional parameters.
use mysql::{Conn,Opts,Params,Row,Value as MyValue,prelude::Queryable};
use std::collections::BTreeMap;
use thiserror::Error;
#[derive(Debug,Clone,PartialEq)]pub enum DbValue{Null,Integer(i64),Unsigned(u64),Real(f64),Text(String),Bytes(Vec<u8>),Date(String),Time(String)}
#[derive(Error,Debug)]pub enum MyError{#[error("MySQL error: {0}")]Mysql(#[from]mysql::Error),#[error("invalid MySQL URL: {0}")]Url(#[from]mysql::UrlError),#[error("transaction already active")]TransactionActive,#[error("no active transaction")]NoTransaction}
pub struct Database{connection:Conn,in_transaction:bool}
impl Database{pub fn connect(url:&str)->Result<Self,MyError>{let options=Opts::from_url(url)?;Ok(Self{connection:Conn::new(options)?,in_transaction:false})}
pub fn execute(&mut self,sql:&str,params:&[DbValue])->Result<u64,MyError>{self.connection.exec_drop(sql,Params::Positional(params.iter().map(to_mysql).collect()))?;Ok(self.connection.affected_rows())}
pub fn query(&mut self,sql:&str,params:&[DbValue])->Result<Vec<BTreeMap<String,DbValue>>,MyError>{let rows:Vec<Row>=self.connection.exec(sql,Params::Positional(params.iter().map(to_mysql).collect()))?;Ok(rows.into_iter().map(row).collect())}
pub fn begin(&mut self)->Result<(),MyError>{if self.in_transaction{return Err(MyError::TransactionActive)}self.connection.query_drop("START TRANSACTION")?;self.in_transaction=true;Ok(())}
pub fn commit(&mut self)->Result<(),MyError>{if !self.in_transaction{return Err(MyError::NoTransaction)}self.connection.query_drop("COMMIT")?;self.in_transaction=false;Ok(())}
pub fn rollback(&mut self)->Result<(),MyError>{if !self.in_transaction{return Err(MyError::NoTransaction)}self.connection.query_drop("ROLLBACK")?;self.in_transaction=false;Ok(())}
pub fn last_insert_id(&self)->u64{self.connection.last_insert_id()}}
impl Drop for Database{fn drop(&mut self){if self.in_transaction{let _=self.connection.query_drop("ROLLBACK");}}}
fn to_mysql(value:&DbValue)->MyValue{match value{DbValue::Null=>MyValue::NULL,DbValue::Integer(value)=>MyValue::Int(*value),DbValue::Unsigned(value)=>MyValue::UInt(*value),DbValue::Real(value)=>MyValue::Double(*value),DbValue::Text(value)=>MyValue::Bytes(value.as_bytes().to_vec()),DbValue::Bytes(value)=>MyValue::Bytes(value.clone()),DbValue::Date(value)|DbValue::Time(value)=>MyValue::Bytes(value.as_bytes().to_vec())}}
fn row(row:Row)->BTreeMap<String,DbValue>{let names:Vec<String>=row.columns_ref().iter().map(|column|column.name_str().into_owned()).collect();row.unwrap().into_iter().enumerate().map(|(index,value)|(names[index].clone(),from_mysql(value))).collect()}
fn from_mysql(value:MyValue)->DbValue{match value{MyValue::NULL=>DbValue::Null,MyValue::Int(value)=>DbValue::Integer(value),MyValue::UInt(value)=>DbValue::Unsigned(value),MyValue::Float(value)=>DbValue::Real(value.into()),MyValue::Double(value)=>DbValue::Real(value),MyValue::Bytes(value)=>String::from_utf8(value).map(DbValue::Text).unwrap_or_else(|error|DbValue::Bytes(error.into_bytes())),MyValue::Date(year,month,day,hour,minute,second,micros)=>DbValue::Date(format!("{year:04}-{month:02}-{day:02} {hour:02}:{minute:02}:{second:02}.{micros:06}")),MyValue::Time(negative,days,hours,minutes,seconds,micros)=>DbValue::Time(format!("{}{days} {hours:02}:{minutes:02}:{seconds:02}.{micros:06}",if negative{"-"}else{""}))}}
#[cfg(test)]mod tests{use super::*;#[test]fn converts_all_mysql_value_variants(){let values=vec![MyValue::NULL,MyValue::Int(-1),MyValue::UInt(1),MyValue::Float(1.5),MyValue::Double(2.5),MyValue::Bytes(b"text".to_vec()),MyValue::Date(2026,7,15,1,2,3,4),MyValue::Time(false,1,2,3,4,5)];assert_eq!(values.into_iter().map(from_mysql).count(),8);}#[test]fn live_mysql_round_trip_when_configured(){let Ok(url)=std::env::var("TITAN_MYSQL_TEST_URL")else{return};let mut db=Database::connect(&url).unwrap();let rows=db.query("SELECT ? AS value",&[DbValue::Integer(42)]).unwrap();assert!(matches!(rows[0]["value"],DbValue::Integer(42)|DbValue::Unsigned(42)));}}
