APT::FTPArchive::Release::Origin "zett";
APT::FTPArchive::Release::Label "zett";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "zett";
APT::FTPArchive::Release::Architectures "arm";
APT::FTPArchive::Release::Components ".";
APT::FTPArchive::Release::Description "Zett APT repository for Termux ARM";
