//! Backtracking SemVer dependency graph resolver.
use crate::registry::{PackageIndex,PackageVersion,RegistryClient,RegistryError};
use serde::{Deserialize,Serialize};
use std::collections::{BTreeMap,HashMap};
use thiserror::Error;
pub trait PackageSource{fn index(&self,name:&str)->Result<PackageIndex,RegistryError>;}
impl PackageSource for RegistryClient{fn index(&self,name:&str)->Result<PackageIndex,RegistryError>{self.fetch_index(name)}}
#[derive(Error,Debug)]pub enum ResolveError{#[error("registry error: {0}")]Registry(#[from]RegistryError),#[error("invalid requirement '{requirement}' for '{package}': {message}")]Requirement{package:String,requirement:String,message:String},#[error("no version of '{package}' satisfies constraints {constraints:?}")]Conflict{package:String,constraints:Vec<String>},#[error("dependency graph exceeds package/decision limits")]Limit}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct LockedRemotePackage{pub name:String,pub version:String,pub archive:String,pub sha256:String,pub signing_key:String,pub signature:String,pub dependencies:BTreeMap<String,String>}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct RemoteLockfile{pub version:u32,pub packages:Vec<LockedRemotePackage>}
struct State{constraints:BTreeMap<String,Vec<String>>,selected:BTreeMap<String,PackageVersion>,decisions:usize}
pub fn resolve(source:&impl PackageSource,roots:&BTreeMap<String,String>,max_packages:usize,max_decisions:usize)->Result<RemoteLockfile,ResolveError>{for(name,requirement)in roots{validate_requirement(name,requirement)?;}let state=State{constraints:roots.iter().map(|(name,requirement)|(name.clone(),vec![requirement.clone()])).collect(),selected:BTreeMap::new(),decisions:0};let mut cache=HashMap::new();let resolved=search(source,state,&mut cache,max_packages,max_decisions)?.ok_or_else(||{let(name,constraints)=roots.iter().next().map(|(name,requirement)|(name.clone(),vec![requirement.clone()])).unwrap_or(("root".into(),Vec::new()));ResolveError::Conflict{package:name,constraints}})?;let packages=resolved.selected.into_iter().map(|(name,release)|LockedRemotePackage{name,version:release.version,archive:release.archive,sha256:release.sha256,signing_key:release.signing_key,signature:release.signature,dependencies:release.dependencies}).collect();Ok(RemoteLockfile{version:1,packages})}
fn search(source:&impl PackageSource,state:State,cache:&mut HashMap<String,PackageIndex>,max_packages:usize,max_decisions:usize)->Result<Option<State>,ResolveError>{if state.constraints.len()>max_packages||state.decisions>max_decisions{return Err(ResolveError::Limit)}for(name,release)in &state.selected{if !matches_all(name,&release.version,state.constraints.get(name).unwrap(),)?{return Ok(None)}}let unresolved=state.constraints.keys().find(|name|!state.selected.contains_key(*name)).cloned();let Some(name)=unresolved else{return Ok(Some(state))};if !cache.contains_key(&name){cache.insert(name.clone(),source.index(&name)?);}let index=cache.get(&name).unwrap();let constraints=state.constraints.get(&name).cloned().unwrap();let mut candidates:Vec<_>=index.versions.iter().filter_map(|release|semver::Version::parse(&release.version).ok().map(|version|(version,release.clone()))).filter(|(version,_)|constraints.iter().all(|requirement|semver::VersionReq::parse(requirement).is_ok_and(|requirement|requirement.matches(version)))).collect();candidates.sort_by(|(left,_),(right,_)|right.cmp(left));for(_,candidate)in candidates{let mut next=State{constraints:state.constraints.clone(),selected:state.selected.clone(),decisions:state.decisions+1};for(dependency,requirement)in &candidate.dependencies{validate_requirement(dependency,requirement)?;next.constraints.entry(dependency.clone()).or_default().push(requirement.clone());}next.selected.insert(name.clone(),candidate);if let Some(result)=search(source,next,cache,max_packages,max_decisions)?{return Ok(Some(result))}}Ok(None)}
fn matches_all(package:&str,version:&str,constraints:&[String])->Result<bool,ResolveError>{let version=semver::Version::parse(version).map_err(|error|ResolveError::Requirement{package:package.into(),requirement:version.into(),message:error.to_string()})?;for requirement in constraints{let parsed=semver::VersionReq::parse(requirement).map_err(|error|ResolveError::Requirement{package:package.into(),requirement:requirement.clone(),message:error.to_string()})?;if !parsed.matches(&version){return Ok(false)}}Ok(true)}
fn validate_requirement(package:&str,requirement:&str)->Result<(),ResolveError>{semver::VersionReq::parse(requirement).map(|_|()).map_err(|error|ResolveError::Requirement{package:package.into(),requirement:requirement.into(),message:error.to_string()})}
impl RemoteLockfile{pub fn to_json(&self)->Result<String,serde_json::Error>{serde_json::to_string_pretty(self).map(|value|value+"\n")}pub fn read(path:&std::path::Path)->Result<Self,std::io::Error>{let text=std::fs::read_to_string(path)?;serde_json::from_str(&text).map_err(|error|std::io::Error::new(std::io::ErrorKind::InvalidData,error))}pub fn write(&self,path:&std::path::Path)->Result<(),std::io::Error>{let text=self.to_json().map_err(|error|std::io::Error::new(std::io::ErrorKind::InvalidData,error))?;let temporary=path.with_extension("lock.tmp");std::fs::write(&temporary,text)?;if path.exists(){std::fs::remove_file(path)?;}std::fs::rename(temporary,path)}}
#[cfg(test)]mod tests{use super::*;struct Mock(BTreeMap<String,PackageIndex>);impl PackageSource for Mock{fn index(&self,name:&str)->Result<PackageIndex,RegistryError>{Ok(self.0[name].clone())}}fn release(version:&str,dependencies:&[(&str,&str)])->PackageVersion{PackageVersion{version:version.into(),archive:format!("https://r/{version}"),sha256:"0".repeat(64),signing_key:"k".into(),signature:"s".into(),dependencies:dependencies.iter().map(|(name,requirement)|((*name).into(),(*requirement).into())).collect()}}#[test]fn backtracks_to_satisfy_all_constraints(){let source=Mock(BTreeMap::from([("a".into(),PackageIndex{name:"a".into(),versions:vec![release("1.0.0",&[("b","^1")]),release("2.0.0",&[("b","^2")])]}),("b".into(),PackageIndex{name:"b".into(),versions:vec![release("1.5.0",&[]),release("2.5.0",&[])]})]));let lock=resolve(&source,&BTreeMap::from([("a".into(),">=1".into()),("b".into(),"^1".into())]),10,100).unwrap();assert_eq!(lock.packages.iter().find(|package|package.name=="a").unwrap().version,"1.0.0");assert_eq!(lock.packages.iter().find(|package|package.name=="b").unwrap().version,"1.5.0");assert!(lock.to_json().unwrap().contains("sha256"));}}
