//! Synchronous PostgreSQL driver with prepared parameters and typed rows.
use postgres::{Client,NoTls,Row,types::{ToSql,Type}};
use std::collections::BTreeMap;
use std::sync::{Arc,Condvar,Mutex};
use std::time::{Duration,Instant};
use thiserror::Error;
#[derive(Debug,Clone,PartialEq)]pub enum DbValue{Null,Bool(bool),Integer(i64),Real(f64),Text(String),Bytes(Vec<u8>),Json(serde_json::Value)}
#[derive(Error,Debug)]pub enum PgError{#[error("PostgreSQL error: {0}")]Postgres(#[from]postgres::Error),#[error("transaction already active")]TransactionActive,#[error("no active transaction")]NoTransaction,#[error("unsupported PostgreSQL column type '{0}'")]UnsupportedType(String),#[error("PostgreSQL pool size must be positive")]PoolSize,#[error("PostgreSQL pool acquisition timed out")]PoolTimeout,#[error("PostgreSQL pool is closed")]PoolClosed,#[error("PostgreSQL pool lock poisoned")]PoolPoisoned}
pub struct Database{client:Client,in_transaction:bool}
impl Database{
pub fn connect(url:&str)->Result<Self,PgError>{Ok(Self{client:Client::connect(url,NoTls)?,in_transaction:false})}
pub fn connect_tls(url:&str)->Result<Self,PgError>{let config=(*titan_tls::client_config()).clone();let tls=tokio_postgres_rustls::MakeRustlsConnect::new(config);Ok(Self{client:Client::connect(url,tls)?,in_transaction:false})}
pub fn execute(&mut self,sql:&str,params:&[DbValue])->Result<u64,PgError>{let values=parameters(params);let refs:Vec<&(dyn ToSql+Sync)>=values.iter().map(|value|value.as_ref()).collect();let statement=self.client.prepare(sql)?;Ok(self.client.execute(&statement,&refs)?)}
pub fn query(&mut self,sql:&str,params:&[DbValue])->Result<Vec<BTreeMap<String,DbValue>>,PgError>{let values=parameters(params);let refs:Vec<&(dyn ToSql+Sync)>=values.iter().map(|value|value.as_ref()).collect();let statement=self.client.prepare(sql)?;self.client.query(&statement,&refs)?.into_iter().map(row).collect()}
pub fn begin(&mut self)->Result<(),PgError>{if self.in_transaction{return Err(PgError::TransactionActive)}self.client.batch_execute("BEGIN")?;self.in_transaction=true;Ok(())}
pub fn commit(&mut self)->Result<(),PgError>{if !self.in_transaction{return Err(PgError::NoTransaction)}self.client.batch_execute("COMMIT")?;self.in_transaction=false;Ok(())}
pub fn rollback(&mut self)->Result<(),PgError>{if !self.in_transaction{return Err(PgError::NoTransaction)}self.client.batch_execute("ROLLBACK")?;self.in_transaction=false;Ok(())}
pub fn cancel(&self)->Result<(),PgError>{self.client.cancel_token().cancel_query(NoTls)?;Ok(())}
}
impl Drop for Database{fn drop(&mut self){if self.in_transaction{let _=self.client.batch_execute("ROLLBACK");}}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub struct PoolStats{pub maximum:usize,pub total:usize,pub idle:usize,pub checked_out:usize,pub closed:bool,pub tls:bool}
struct PoolState{idle:Vec<Database>,total:usize,closed:bool}
struct PoolInner{url:String,maximum:usize,tls:bool,state:Mutex<PoolState>,available:Condvar}
#[derive(Clone)]pub struct Pool(Arc<PoolInner>);pub struct PooledConnection{database:Option<Database>,pool:Arc<PoolInner>}
impl Pool{pub fn new(url:impl Into<String>,maximum:usize,tls:bool)->Result<Self,PgError>{if maximum==0{return Err(PgError::PoolSize)}Ok(Self(Arc::new(PoolInner{url:url.into(),maximum,tls,state:Mutex::new(PoolState{idle:Vec::new(),total:0,closed:false}),available:Condvar::new()})))}
pub fn acquire(&self,timeout:Duration)->Result<PooledConnection,PgError>{let deadline=Instant::now()+timeout;loop{let mut state=self.0.state.lock().map_err(|_|PgError::PoolPoisoned)?;if state.closed{return Err(PgError::PoolClosed)}
if let Some(database)=state.idle.pop(){return Ok(PooledConnection{database:Some(database),pool:Arc::clone(&self.0)})}
if state.total<self.0.maximum{state.total+=1;drop(state);let result=if self.0.tls{Database::connect_tls(&self.0.url)}else{Database::connect(&self.0.url)};match result{Ok(database)=>return Ok(PooledConnection{database:Some(database),pool:Arc::clone(&self.0)}),Err(error)=>{let mut state=self.0.state.lock().map_err(|_|PgError::PoolPoisoned)?;state.total-=1;self.0.available.notify_one();return Err(error)}}}let remaining=deadline.saturating_duration_since(Instant::now());if remaining.is_zero(){return Err(PgError::PoolTimeout)}let(_state_after_wait,wait)=self.0.available.wait_timeout(state,remaining).map_err(|_|PgError::PoolPoisoned)?;if wait.timed_out(){return Err(PgError::PoolTimeout)}}}
pub fn stats(&self)->Result<PoolStats,PgError>{let state=self.0.state.lock().map_err(|_|PgError::PoolPoisoned)?;Ok(PoolStats{maximum:self.0.maximum,total:state.total,idle:state.idle.len(),checked_out:state.total-state.idle.len(),closed:state.closed,tls:self.0.tls})}pub fn close(&self)->Result<(),PgError>{let mut state=self.0.state.lock().map_err(|_|PgError::PoolPoisoned)?;state.closed=true;let idle=state.idle.len();state.idle.clear();state.total-=idle;self.0.available.notify_all();Ok(())}}
impl std::ops::Deref for PooledConnection{type Target=Database;fn deref(&self)->&Self::Target{self.database.as_ref().expect("pool invariant")}}impl std::ops::DerefMut for PooledConnection{fn deref_mut(&mut self)->&mut Self::Target{self.database.as_mut().expect("pool invariant")}}impl Drop for PooledConnection{fn drop(&mut self){let Some(database)=self.database.take()else{return};if let Ok(mut state)=self.pool.state.lock(){if state.closed{state.total=state.total.saturating_sub(1)}else{state.idle.push(database)}self.pool.available.notify_one();}}}
fn parameters(values:&[DbValue])->Vec<Box<dyn ToSql+Sync>>{values.iter().map(|value|match value{DbValue::Null=>Box::new(None::<String>)as Box<dyn ToSql+Sync>,DbValue::Bool(value)=>Box::new(*value),DbValue::Integer(value)=>Box::new(*value),DbValue::Real(value)=>Box::new(*value),DbValue::Text(value)=>Box::new(value.clone()),DbValue::Bytes(value)=>Box::new(value.clone()),DbValue::Json(value)=>Box::new(value.clone())}).collect()}
fn row(row:Row)->Result<BTreeMap<String,DbValue>,PgError>{let mut output=BTreeMap::new();for(index,column)in row.columns().iter().enumerate(){let value=match column.type_(){&Type::BOOL=>nullable(&row,index,DbValue::Bool)?,&Type::INT2=>nullable(&row,index,|value:i16|DbValue::Integer(value.into()))?,&Type::INT4=>nullable(&row,index,|value:i32|DbValue::Integer(value.into()))?,&Type::INT8=>nullable(&row,index,DbValue::Integer)?,&Type::FLOAT4=>nullable(&row,index,|value:f32|DbValue::Real(value.into()))?,&Type::FLOAT8=>nullable(&row,index,DbValue::Real)?,&Type::TEXT|&Type::VARCHAR|&Type::BPCHAR|&Type::NAME=>nullable(&row,index,DbValue::Text)?,&Type::BYTEA=>nullable(&row,index,DbValue::Bytes)?,&Type::JSON|&Type::JSONB=>nullable(&row,index,DbValue::Json)?,other=>return Err(PgError::UnsupportedType(other.name().into()))};output.insert(column.name().into(),value);}Ok(output)}
fn nullable<T>(row:&Row,index:usize,convert:impl FnOnce(T)->DbValue)->Result<DbValue,postgres::Error>where T:for<'a>postgres::types::FromSql<'a>{Ok(row.try_get::<_,Option<T>>(index)?.map(convert).unwrap_or(DbValue::Null))}
#[cfg(test)]mod tests{use super::*;#[test]fn validates_pool_lifecycle_without_connecting(){assert!(matches!(Pool::new("postgresql://localhost/test",0,false),Err(PgError::PoolSize)));let pool=Pool::new("postgresql://localhost/test",1,true).unwrap();assert!(pool.stats().unwrap().tls);pool.close().unwrap();assert!(matches!(pool.acquire(Duration::ZERO),Err(PgError::PoolClosed)));}#[test]fn builds_rustls_connector(){let config=(*titan_tls::client_config()).clone();let _connector=tokio_postgres_rustls::MakeRustlsConnect::new(config);}#[test]fn parameter_conversion_covers_supported_types(){let values=vec![DbValue::Null,DbValue::Bool(true),DbValue::Integer(1),DbValue::Real(1.5),DbValue::Text("x".into()),DbValue::Bytes(vec![1]),DbValue::Json(serde_json::json!({"x":1}))];assert_eq!(parameters(&values).len(),values.len());}#[test]fn live_postgres_round_trip_when_configured(){let Ok(url)=std::env::var("TITAN_POSTGRES_TEST_URL")else{return};let mut db=Database::connect(&url).unwrap();let row=db.query("SELECT $1::bigint AS value",&[DbValue::Integer(42)]).unwrap();assert_eq!(row[0]["value"],DbValue::Integer(42));}}
