[package]
name = "titan_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
titan_lexer = { path = "../titan_lexer" }
titan_parser = { path = "../titan_parser" }
titan_ast = { path = "../titan_ast" }
titan_typechecker = { path = "../titan_typechecker" }
titan_codegen = { path = "../titan_codegen" }
titan_vm = { path = "../titan_vm" }
titan_pkg = { path = "../titan_pkg" }
titan_wasm = { path = "../titan_wasm" }
clap.workspace = true
thiserror.workspace = true

[[bin]]
name = "titan"
path = "src/main.rs"
