//! Bounded multipart/form-data parser for HTTP uploads.
use std::collections::BTreeMap;
use thiserror::Error;
#[derive(Debug,Clone,PartialEq,Eq)]pub struct Part{pub name:String,pub filename:Option<String>,pub content_type:Option<String>,pub headers:BTreeMap<String,String>,pub data:Vec<u8>}
#[derive(Error,Debug,Clone,PartialEq,Eq)]pub enum MultipartError{#[error("missing or invalid multipart boundary")]Boundary,#[error("malformed multipart body")]Malformed,#[error("multipart part count exceeds limit")]TooManyParts,#[error("multipart part exceeds size limit")]PartTooLarge,#[error("multipart headers exceed limits")]Headers,#[error("multipart Content-Disposition is invalid")]Disposition}
pub fn boundary(content_type:&str)->Result<String,MultipartError>{let mut parts=content_type.split(';');if !parts.next().is_some_and(|value|value.trim().eq_ignore_ascii_case("multipart/form-data")){return Err(MultipartError::Boundary)}for parameter in parts{let Some((name,value))=parameter.trim().split_once('=')else{continue};if name.trim().eq_ignore_ascii_case("boundary"){let value=value.trim().trim_matches('"');if value.is_empty()||value.len()>70||value.bytes().any(|byte|byte.is_ascii_control()||byte==b' '){return Err(MultipartError::Boundary)}return Ok(value.into())}}Err(MultipartError::Boundary)}
pub fn parse(content_type:&str,body:&[u8],max_parts:usize,max_part_bytes:usize)->Result<Vec<Part>,MultipartError>{let boundary=boundary(content_type)?;let delimiter=format!("--{boundary}").into_bytes();if !body.starts_with(&delimiter){return Err(MultipartError::Malformed)}let mut cursor=delimiter.len();let mut output=Vec::new();loop{if body.get(cursor..cursor+2)==Some(b"--"){cursor+=2;if body.get(cursor..).is_some_and(|rest|rest.is_empty()||rest==b"\r\n"){return Ok(output)}return Err(MultipartError::Malformed)}
if body.get(cursor..cursor+2)!=Some(b"\r\n"){return Err(MultipartError::Malformed)}cursor+=2;let header_end=find(&body[cursor..],b"\r\n\r\n").ok_or(MultipartError::Malformed)?;if header_end>16*1024{return Err(MultipartError::Headers)}let header_text=std::str::from_utf8(&body[cursor..cursor+header_end]).map_err(|_|MultipartError::Headers)?;let mut headers=BTreeMap::new();for(index,line)in header_text.split("\r\n").enumerate(){if index>=32{return Err(MultipartError::Headers)}let(name,value)=line.split_once(':').ok_or(MultipartError::Headers)?;if name.is_empty()||value.contains(['\r','\n']){return Err(MultipartError::Headers)}headers.insert(name.to_ascii_lowercase(),value.trim().into());}cursor+=header_end+4;let mut marker=b"\r\n".to_vec();marker.extend_from_slice(&delimiter);let data_end=find(&body[cursor..],&marker).ok_or(MultipartError::Malformed)?;if data_end>max_part_bytes{return Err(MultipartError::PartTooLarge)}
if output.len()>=max_parts{return Err(MultipartError::TooManyParts)}let disposition=headers.get("content-disposition").ok_or(MultipartError::Disposition)?;let(name,filename)=parse_disposition(disposition)?;let content_type=headers.get("content-type").cloned();output.push(Part{name,filename,content_type,headers,data:body[cursor..cursor+data_end].to_vec()});cursor+=data_end+2+delimiter.len();}}
fn parse_disposition(value:&str)->Result<(String,Option<String>),MultipartError>{let mut pieces=value.split(';');if !pieces.next().is_some_and(|value|value.trim().eq_ignore_ascii_case("form-data")){return Err(MultipartError::Disposition)}let mut name=None;let mut filename=None;for piece in pieces{let Some((key,value))=piece.trim().split_once('=')else{continue};let value=value.trim().trim_matches('"');if value=="."||value==".."||value.contains(['\r','\n','/','\\']){return Err(MultipartError::Disposition)}match key.trim(){"name"=>name=Some(value.into()),"filename"=>filename=Some(value.into()),_=>{}}}Ok((name.filter(|value:&String|!value.is_empty()).ok_or(MultipartError::Disposition)?,filename))}
fn find(haystack:&[u8],needle:&[u8])->Option<usize>{haystack.windows(needle.len()).position(|window|window==needle)}
#[cfg(test)]mod tests{use super::*;#[test]fn parses_text_and_file_parts(){let body=b"--abc\r\nContent-Disposition: form-data; name=\"title\"\r\n\r\nTitan\r\n--abc\r\nContent-Disposition: form-data; name=\"file\"; filename=\"a.txt\"\r\nContent-Type: text/plain\r\n\r\nhello\r\n--abc--\r\n";let parts=parse("multipart/form-data; boundary=abc",body,4,1024).unwrap();assert_eq!(parts.len(),2);assert_eq!(parts[0].data,b"Titan");assert_eq!(parts[1].filename.as_deref(),Some("a.txt"));}#[test]fn enforces_limits_and_safe_filenames(){let body=b"--x\r\nContent-Disposition: form-data; name=\"f\"; filename=\"../bad\"\r\n\r\na\r\n--x--\r\n";assert_eq!(parse("multipart/form-data; boundary=x",body,2,10),Err(MultipartError::Disposition));assert!(parse("text/plain",b"",1,1).is_err());}}
