[package]
name = "titan_codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
titan_ast = { path = "../titan_ast" }
titan_lexer = { path = "../titan_lexer" }
titan_typechecker = { path = "../titan_typechecker" }
titan_stdlib = { path = "../titan_stdlib" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
titan_parser = { path = "../titan_parser" }
